.PHONY: local-server

## Build Mock OCM Server Binary
build-local-server:
	go build -o ./bin/local-server ./test/

## Start Mock OCM Server Binary
start-local-server:
	./bin/local-server

## Run Mock OCM Server Binary
run-local-server: build-local-server start-local-server

## Build Mock OCM Server Image
build-local-server-image:
	docker build . -f build/Dockerfile.local-server -t quay.io/rhibmcollab/mock-ocm-server:latest

## Push Mock OCM Server Image
push-local-server-image: build-local-server-image
	docker push quay.io/rhibmcollab/mock-ocm-server:latest

## Run Mock OCM Server Image Locally
run-local-server-image:
	docker run -p 8080:8080 quay.io/rhibmcollab/mock-ocm-server:latest

## Annotate DiscoveryConfig with Mock OCM Server URL
annotate-discovery-config:
	oc annotate discoveryconfig discoveryconfig OCM_URL=http://mock-ocm-server.open-cluster-management.svc.cluster.local:8080 --overwrite

## Run Mock OCM Server Image In Cluster
run-mock-ocm-server: push-local-server-image
	oc apply -k build/local-server