apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: discovery-operator-webhook-service
  creationTimestamp: null
  name: discovery-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: discovery-operator
status:
  loadBalancer: {}
