---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: discovery-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/accept
  - managedclusters/finalizers
  - managedclustersets
  - managedclustersets/bind
  - managedclustersets/finalizers
  - managedclustersets/join
  - managedclustersetbindings
  - managedclustersetbindings/finalizers
  - placements
  - placements/finalizers
  - managedclusters/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agent.open-cluster-management.io
  resources:
    - klusterletaddonconfigs
    - klusterletaddonconfigs/finalizers
    - klusterletaddonconfigs/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
