# Copyright Contributors to the Open Cluster Management project

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/discovery.open-cluster-management.io_discoveredclusters.yaml
- bases/discovery.open-cluster-management.io_discoveryconfigs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesJson6902:
- path: patches/deprecation_warning_discoveredclusters.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: discoveredclusters.discovery.open-cluster-management.io
- path: patches/deprecation_warning_discoveryconfigs.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: discoveryconfigs.discovery.open-cluster-management.io
    
patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_discoveredclusters.yaml
#- patches/webhook_in_discoveryconfigs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_discoveredclusters.yaml
#- patches/cainjection_in_discoveryconfigs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
